const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";
const PRODUCT_DETAIL_REQUEST = "PRODUCT_DETAIL_REQUEST";
const PRODUCT_DETAIL_SUCCESS = "PRODUCT_DETAIL_SUCCESS";
const PRODUCT_DETAIL_FAIL = "PRODUCT_DETAIL_FAIL";
const ADD_TO_CART = "ADD_TO_CART";
const REMOVE_ITEM = "REMOVE_ITEM";
const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
const SIGN_IN_FAIL = "SIGN_IN_FAIL";
const SIGN_IN_REQUEST = "SIGN_IN_REQUEST";
const REGISTER_REQUEST = "REGISTER_REQUEST";
const REGISTER_FAIL = "REGISTER_FAIL";
const REGISTER_SUCCESS = "REGISTER_SUCCESS";
const LOG_OUT = "LOG_OUT";
const PRODUCT_SAVE_REQUEST = "PRODUCT_SAVE_REQUEST";
const PRODUCT_SAVE_FAIL = "PRODUCT_SAVE_FAIL";
const PRODUCT_SAVE_SUCCESS = "PRODUCT_SAVE_PRODUCT_SAVE_SUCCESS";
const PRODUCT_DELETE_REQUEST = "PRODUCT_DELETE_REQUEST";
const PRODUCT_DELETE_FAIL = "PRODUCT_DELETE_FAIL";
const PRODUCT_DELETE_SUCCESS = "PRODUCT_DELETE_SUCCESS";
const SHIPPING_INFO = "SHIPPING_INFO";
const PAYMENT_INFO = "PAYMENT_INFO";
const REMOVE_SHIPPING_INFO = "REMOVE_SHIPPING_INFO";
const REMOVE_PAYMENT_INFO = "REMOVE_PAYMENT_INFO";
const REMOVE_CART_ITEMS = "REMOVE_CART_ITEMS";
const REVIEW_SUCCESS = "REVIEW_SUCCESS";
const REVIEW_FAIL = "REVIEW_FAIL";
const REVIEW_REQUEST = "REVIEW_REQUEST";
const ORDER_FAIL = "ORDER_FAIL";
const ORDER_SUCCESS = "ORDER_SUCCESS";
const ORDER_REQUEST = "ORDER_REQUEST";
const DETAIL_ORDER_SUCCESS = "DETAIL_ORDER_SUCCESS";
const DETAIL_ORDER_FAIL = "DETAIL_ORDER_FAILS";
const DETAIL_ORDER_REQUEST = "DETAIL_ORDER_REQUEST";
const SEARCH_REQUEST = "SEARCH_REQUEST";
const SEARCH_FAIL = "SEARCH_FAIL";
const SEARCH_SUCCESS = "SEARCH_SUCCESS";

export {
  PRODUCT_LIST_REQUEST,
  PRODUCT_LIST_SUCCESS,
  PRODUCT_LIST_FAIL,
  PRODUCT_DETAIL_REQUEST,
  PRODUCT_DETAIL_FAIL,
  PRODUCT_DETAIL_SUCCESS,
  ADD_TO_CART,
  REMOVE_ITEM,
  SIGN_IN_SUCCESS,
  SIGN_IN_REQUEST,
  SIGN_IN_FAIL,
  REGISTER_REQUEST,
  REGISTER_FAIL,
  REGISTER_SUCCESS,
  LOG_OUT,
  PRODUCT_SAVE_REQUEST,
  PRODUCT_SAVE_FAIL,
  PRODUCT_SAVE_SUCCESS,
  PRODUCT_DELETE_REQUEST,
  PRODUCT_DELETE_FAIL,
  PRODUCT_DELETE_SUCCESS,
  SHIPPING_INFO,
  PAYMENT_INFO,
  REMOVE_PAYMENT_INFO,
  REMOVE_SHIPPING_INFO,
  REMOVE_CART_ITEMS,
  REVIEW_SUCCESS,
  REVIEW_FAIL,
  REVIEW_REQUEST,
  ORDER_FAIL,
  ORDER_REQUEST,
  ORDER_SUCCESS,
  DETAIL_ORDER_REQUEST,
  DETAIL_ORDER_SUCCESS,
  DETAIL_ORDER_FAIL,
  SEARCH_REQUEST,
  SEARCH_FAIL,
  SEARCH_SUCCESS,
};
